# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: create virtual environment for python
    before:  |
      (
        set -e
        cd ..
        python3 -m venv npf_venv
      )
  - name: Installing dependencies
    init: |
      (
        set -e
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
      )
  - name: test
    command: echo 'command script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# ports:
#   - port: 3000
#     onOpen: open-preview
