# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: move to parent folder
    before: echo 'before script'
  - init: |
      (
        set -e # Tells bash to immediately exit on failure off a command
        cd ..
        python3 -m venv npf_venv
      )
    command: echo 'command script'

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
