# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Pre Init
    before:  |
      (
        echo 'tbd'
      )
  - name: Installing dependencies
    init: |
      (
        set -e
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        gp sync-done installation
      )
  - name: run dev server
    init: gp sync-await installation
    command: |
      (
        set -e
        cd src/non-plastic-info/
        uvicorn main:app --reload
      )

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true