# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Copy requirements.txt content
    before:  |
      (
        cp requirements.txt src/non-plastic-info/app_requirements.txt
      )
  - name: Installing dependencies
    init: |
      (
        set -e
        python3 -m pip install --upgrade pip
        python3 -m pip install -r requirements.txt
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        kubectl version --client --output=yaml
        gp sync-done installation
      )
  - name: run dev server
    init: gp sync-await installation
    command: |
      (
        set -e
        cd src/non-plastic-info/
        uvicorn main:app --reload
      )
    openMode: tab-after
  - name: build docker image
    init: gp sync-await installation
    command: |
      (
        cd src/non-plastic-info/
        docker build -t devimage .
        # docker run --name dev -p 80:80 devImage # optional and disabled by default
      )

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - name: non-plastic-info Api
    description: The non plastic info dev server
    port: 8000
    onOpen: open-preview
  - name: non-plastic-info Api (Docker)
    description: The non plastic info dev server in a docker container
    port: 80
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true